In [ ]:
#Regression

In [2]:
#mounnt your google dirve
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
#Example 7.1

# Import the College data file and label it myData

import pandas as pd
myData = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/MH-Ch7/jaggia_ba_2025_ch07_data.xlsx', sheet_name = 'College')
myData.head()

                              School  Earnings   Cost  Grad  Debt  Location
0                 St. Ambrose C (NC)     44800  22920    62    88      City
1        Albion College (Albion, MI)     45100  23429    73    92  Non-city
2     Alfred University (Alfred, NY)     42300  19567    63    87  Non-city
3  Allegheny College (Meadville, PA)     49200  25147    78    92  Non-city
4        Beloit College (Beloit, WI)     37900  21979    78    93      City

In [ ]:
# Creating City dummy variable

# This is what our textbook used:
#Create the City column --> 1 for 'City, 0 for Non-city.

myData['City'] = myData['Location'].apply(lambda x: 1 if x == 'City' else 0)
print(myData.head())

In [6]:
import numpy as np

# Another way to create the City column --> 1 for 'City', 0 for Non-city

myData['City'] = np.where(myData['Location'] == 'City', 1, 0)
myData

,School,Earnings,Cost,Grad,Debt,Location,City
0,St. Ambrose C (NC),44800,22920,62,88,City,1
1,"Albion College (Albion, MI)",45100,23429,73,92,Non-city,0
2,"Alfred University (Alfred, NY)",42300,19567,63,87,Non-city,0
3,"Allegheny College (Meadville, PA)",49200,25147,78,92,Non-city,0
4,"Beloit College (Beloit, WI)",37900,21979,78,93,City,1
...,...,...,...,...,...,...,...
111,"Whittier College (Whittier, CA)",45100,33181,67,86,Non-city,0
112,"Widener University (Chester, PA)",51700,27387,56,83,Non-city,0
113,"Willamette University (Salem, OR)",49200,30312,78,93,City,1
114,"Winthrop University (Rock Hill, SC)",36100,15311,54,76,City,1
115,"Wittenberg University (Springfield, OH)",42700,26616,64,90,City,1

In [11]:
# Obtaining regression output
import statsmodels.formula.api as smf
Model = smf.ols('Earnings ~ Cost + Grad + Debt + City', data = myData).fit()
Model

In [12]:
print(Model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               Earnings   R-squared:                       0.429
Model:                            OLS   Adj. R-squared:                  0.409
Method:                 Least Squares   F-statistic:                     20.87
Date:                Tue, 04 Nov 2025   Prob (F-statistic):           7.56e-13
Time:                        19:06:01   Log-Likelihood:                -1164.1
No. Observations:                 116   AIC:                             2338.
Df Residuals:                     111   BIC:                             2352.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept       1e+04   7634.334      1.311      0.193   -5122.976    2.51e+04
Cost           0.4349      0.111      3.917      0.000       0.215       0.655
Grad         178.0989     69.194      2.574      0.011      40.986     315.211
Debt         141.4783    117.212      1.207      0.230     -90.785     373.742
City        2526.7888   1103.403      2.290      0.024     340.323    4713.255
==============================================================================
Omnibus:                       14.990   Durbin-Watson:                   1.973
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               20.512
Skew:                           0.669   Prob(JB):                     3.51e-05
Kurtosis:                       4.566   Cond. No.                     3.76e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.76e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [22]:
print(Model.predict(pd.DataFrame({'Cost': [25000], 'Grad': [60],'Debt': [80],'City': [1] })))

0    45408.799089
dtype: float64

### Example 7.2

In [13]:


import pandas as pd
myData = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/MH-Ch7/jaggia_ba_2025_ch07_data.xlsx', sheet_name = 'College')
myData.head()

                              School  Earnings   Cost  Grad  Debt  Location
0                 St. Ambrose C (NC)     44800  22920    62    88      City
1        Albion College (Albion, MI)     45100  23429    73    92  Non-city
2     Alfred University (Alfred, NY)     42300  19567    63    87  Non-city
3  Allegheny College (Meadville, PA)     49200  25147    78    92  Non-city
4        Beloit College (Beloit, WI)     37900  21979    78    93      City

In [19]:
# Creating City dummy variable
myData['City'] = myData['Location'].apply(lambda x: 1 if x == 'City' else 0)

In [20]:
import statsmodels.formula.api as smf
Model = smf.ols('Earnings ~ Cost + Grad + Debt + City', data = myData).fit()
print(Model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               Earnings   R-squared:                       0.429
Model:                            OLS   Adj. R-squared:                  0.409
Method:                 Least Squares   F-statistic:                     20.87
Date:                Tue, 04 Nov 2025   Prob (F-statistic):           7.56e-13
Time:                        19:08:46   Log-Likelihood:                -1164.1
No. Observations:                 116   AIC:                             2338.
Df Residuals:                     111   BIC:                             2352.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept       1e+04   7634.334      1.311      0.193   -5122.976    2.51e+04
Cost           0.4349      0.111      3.917      0.000       0.215       0.655
Grad         178.0989     69.194      2.574      0.011      40.986     315.211
Debt         141.4783    117.212      1.207      0.230     -90.785     373.742
City        2526.7888   1103.403      2.290      0.024     340.323    4713.255
==============================================================================
Omnibus:                       14.990   Durbin-Watson:                   1.973
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               20.512
Skew:                           0.669   Prob(JB):                     3.51e-05
Kurtosis:                       4.566   Cond. No.                     3.76e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.76e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [21]:
print(Model.get_prediction(pd.DataFrame({'Cost': [25000], 'Grad': [60],'Debt': [80],'City': [1]})).summary_frame(alpha = .05))

           mean      mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  \
0  45408.799089  1017.280834   43392.989207   47424.608971  34041.052382

   obs_ci_upper
0  56776.545796